openapi: 3.0.0
info:
  title: Diploma Management API
  version: 1.0.0
  description: >
    API for managing diploma assignments, users (students, professors, secretaries) and data imports.

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /secretary:
    post:
      summary: Create a new secretary user
      tags:
        - Secretary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - name
                - email
              properties:
                username:
                  type: string
                  example: secr1
                password:
                  type: string
                  example: test1234
                name:
                  type: string
                  example: Ελένη Γραμματεία
                email:
                  type: string
                  format: email
                  example: eleni@upatras.gr
                department:
                  type: string
                  example: Μηχανικών Η/Υ
      responses:
        '201':
          description: Secretary created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Secretary'
        '400':
          description: Bad request (e.g. username exists)

  /secretary/{username}:
    get:
      summary: Get a secretary by username
      tags:
        - Secretary
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
          example: secr1
      responses:
        '200':
          description: Secretary found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Secretary'
        '404':
          description: Secretary not found

    put:
      summary: Update a secretary by username
      tags:
        - Secretary
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
          example: secr1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Νέα Γραμματεία
                email:
                  type: string
                  example: newemail@upatras.gr
                department:
                  type: string
                  example: Νέο Τμήμα
                password:
                  type: string
                  example: newpassword
      responses:
        '200':
          description: Secretary updated successfully
        '404':
          description: Secretary not found

    delete:
      summary: Delete a secretary by username
      tags:
        - Secretary
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
          example: secr1
      responses:
        '200':
          description: Secretary deleted successfully
        '404':
          description: Secretary not found

components:
  schemas:
    Secretary:
      type: object
      properties:
        _id:
          type: string
        username:
          type: string
        name:
          type: string
        email:
          type: string
        department:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
